### ISSUE TITLE
按照你提供的方法执行，报下面错误，请指导下

### ISSUE THREAD

**Issue by lihua123569** [seregaSLM/proguard-spring-boot-example#1]
[ERROR] Failed to execute goal com.github.wvengen:proguard-maven-plugin:2.0.14:p
roguard (default) on project baseDemoO-web: Obfuscation failed (result=1) -> [He
lp 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :baseDemoO-web

**Comment by seregaSLM** [comment]
I updated the instructions and you can find there the possible cause of the error.
