### ISSUE TITLE
Could not find or load main class com.slm.proguard.example.spring.boot.Application

### ISSUE THREAD

**Issue by Jerrick** [seregaSLM/proguard-spring-boot-example#2]
After packaging the project, I run it on mac and centos，but get this exception：
_Error: Could not find or load main class com.slm.proguard.example.spring.boot.Application_

My command is：
_java -cp spring.boot.jar.:$CLASSPATH com.slm.proguard.example.spring.boot.Application_

My env is based JDK8，so I modifed the pom.xml

diff --git a/pom.xml b/pom.xml
     </parent>
     <properties>
-        <java.version>11</java.version>

Thanks

**Comment by seregaSLM** [comment]
Thanks fo the issue.
I missed this info in the README file and now added a description about editing the **java.version** parameter in accordance with the using JDK version.
