### ISSUE TITLE
run spring boot jar error

### ISSUE THREAD

**Issue by fangjilue** [seregaSLM/proguard-spring-boot-example#3]
java -jar xxx.jar 
 
java.lang.IllegalStateException: Unable to open nested entry 'BOOT-INF/lib/xxxxxxxxx.jar'. It has been compressed and nested jar files must be stored without compression. Please check the mechanism used to create your executable jar file

**Comment by seregaSLM** [comment]
Thanks for the issue and could you tell me what version do you use: 2.0 or 1.1?

**Comment by fangjilue** [comment]
v1.1.0

> Thanks for the issue and could you tell me what version do you use: 2.0 or 1.1?
