### ISSUE TITLE
no main manifest attribute, in spring.boot_proguard_base.jar

### ISSUE THREAD

**Issue by anudeepmadrampalli** [seregaSLM/proguard-spring-boot-example#4]
When I try to run the spring.boot_proguard_base.jar, JRE says "no main manifest attribute, in spring.boot_proguard_base.jar". The manifest files are missing in the obfuscated jar. Also can the jar which is built is not in spring boot format. Can you please let me know if you have tested the jar after obfuscation.

**Comment by seregaSLM** [comment]
Thanks for the question!
After compiling the project un the target directory you can see 2 jar files: ```spring.boot_proguard_base.jar``` and ```spring.boot.jar```. The first binary doesn't contain any libs and manifest and its size is about 10kb. You must use ```spring.boot.jar```, it contain all required libs and its size is about 19Mb. I will add this information to the README.
I test every change in different Docker containers with JDK 8 and 11.
