### ISSUE TITLE
Can't find common super class of [com/fasterxml/jackson/databind/ObjectMapper]

### ISSUE THREAD

**Issue by anhlt309** [seregaSLM/proguard-spring-boot-example#5]
My project using jackson lib, when build occur error:
[proguard]   Exception   = [java.lang.IllegalArgumentException] (Can't find common super class of [com/fasterxml/jackson/databind/ObjectMapper] (with 3 known super classes) and [com/fasterxml/jackson/core/JsonProcessingException] (with 1 known super classes))
 [proguard] Error: Can't find common super class of [com/fasterxml/jackson/databind/ObjectMapper] (with 3 known super classes) and [com/fasterxml/jackson/core/JsonProcessingException] (with 1 known super classes)

**Comment by seregaSLM** [comment]
Hello!
I'll try to reproduce this problem.

**Comment by anhlt309** [comment]
I uncomment this line:
`<lib>${java.home}/lib/rt.jar</lib>`
And it works well now. Thanks!
