### ISSUE TITLE
How to convert jar to war after obfuscation?

### ISSUE THREAD

**Issue by pavangayakwad** [seregaSLM/proguard-spring-boot-example#6]
I am obfuscating java spring boot REST API project, the obfuscation works fine and when I run the obfuscated jar with command line `java -jar my_rest_api_app.jar` it work fine! but when I rename the `.jar` file to `.war` and deploy it on tomcat server, it throws error. What am I missing here? please guide!

![image](https://user-images.githubusercontent.com/1834890/134243434-0e8c1c59-869f-42b6-bc99-6627d14bd4cc.png)

**Comment by devslm** [comment]
Hi!
I think you can’t just rename jar to war because the directory structure can be different and spring boot require some dependencies for servlet.
I’ll try to check this problem.

**Comment by pavangayakwad** [comment]
Looking forward to it.

**Comment by devslm** [comment]
I tried to start the war web service but it still fails. The code that I got I pushed to the **feature/add-servlet-example** branch.  The idea is to obfuscate classes before packing the war and then run repackage war.
You can see it and maybe you can find some useful ideas.

**Comment by pavangayakwad** [comment]
Thanks for taking time, looking into it and responding promptly! I will sure check and revert if I make some progress.
